[theme]
primaryColor = "#f63366"  # Optional: Customize primary color if you want
backgroundColor = "#ffffff"  # White background for light mode
secondaryBackgroundColor = "#f0f0f5"  # Lighter background color for secondary elements
textColor = "#000000"  # Black text for light mode
font = "sans serif"  # Default font
